### PR TITLE
Deny to use the same step twice in the story.

### PR DESCRIPTION
**Pull request by ghost**
Things let to do in this pull request:
- [ ] test composition without inheritance
- [ ] test injection of the same substory twice into different arguments of the parent story
- [ ] test usage of the same method with different name when the same method stored as class attribute
- [ ] fix found failures in existing tests

### CODE REVIEW

**Comment by thedrow** [comment]
Why? What if I want to call a step multiple times?
For example if we were to implement bcrypt using stories we'd probably have to repeat the `hash_iteration` step multiple times and it'd be nice to be able to display this to the user.

**Comment by proofit404** [comment]
index
In that case, we'll have a problem with `Skip` jumping to the wrong place.

**Comment by thedrow** [comment]
I can't really see what's going on there.

**Comment by proofit404** [comment]
Skip marker jumps to the end of the story.

**Comment by proofit404** [comment]
Superseded by #460

**Pull request closed without merging**
