### PR TITLE
Setup xenon tool.

### PR DESCRIPTION
**Pull request by proofit404**

### CODE REVIEW

**Comment by thedrow** [comment]
I've reduced our thresholds to our existing ratings.
As we improve our code, we should raise the thresholds for modules and blocks.

**Comment by thedrow** [comment]
Why doesn't the build trigger?

**Comment by thedrow** [comment]
That doesn't trigger the build too...

**Comment by proofit404** [comment]
- [ ] Reopen from the initial state.
- [ ] Fix our codebase to match the `A` standard.

**Pull request closed without merging**
